/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.andihasan7.salam

class Sapa {
    fun salamSapa(name: String): String = "hai $name, selamat datang di Indomaret :)"

    fun main() {

        println(salamSapa("Andi"))
    }
}
